### ISSUE TITLE
Need Parsing module

### ISSUE THREAD

**Issue by zifn** [zifn/CS289_Coltrims_ML#5]
This module would include read and write functions for the various data types being used.

Most important would be to read and write csv files containing the data. Potentially this would require reading an additional user defined yaml file containing additional experimental parameters that would be useful for the analysis. Such a yaml file might include the mass of each ion fragment, photon energy, and the path to the momentum data. Such a file should probably live in the ignored "privileged" folder.

 - [ ] Read and Write CSV files containing the momentum information
 - [ ] Read and write yaml files containing experimental metadata

testing of these functions could be as simple as writing a known file then reading that file and seeing if the read information is equal to the data that was initially written

**Comment by sajantanand** [comment]
Columns of data: Ion 1 (3 p's), Ion 2, Neutral, Electron 1, Electron 2

**Comment by sajantanand** [comment]
To test the parsing module, generate test data in CSV format and ensure that our module produces the expected results.
